/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nlt.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author OM
 */
public class TablePracticeFrame extends javax.swing.JFrame {

    Connection con;
    Statement smt;

    /**
     * Creates new form TablePracticeFrame
     */
    public TablePracticeFrame() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/nlt", "root", "");

            smt = con.createStatement();

            setTableData();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e, "Persons CRUDE", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        recordTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        personsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        personsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personsTable);

        jPanel1.add(jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECTED RECORD:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        recordTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(recordTextField);

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personsTableMouseClicked
        // TODO add your handling code here:
        getSelectedRecord();
    }//GEN-LAST:event_personsTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablePracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablePracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablePracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablePracticeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablePracticeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable personsTable;
    private javax.swing.JTextField recordTextField;
    // End of variables declaration//GEN-END:variables

    public void setTableData() {
        try {

            ResultSet rs = smt.executeQuery("select * from persons where status = 1");
            rs.last();
            int size = rs.getRow();
            rs.beforeFirst();
            String[] cols = {"ID", "NAME", "AGE"};
            String[][] data = new String[size][3];
            int i = 0;
            while (rs.next()) {

                data[i][0] = rs.getInt("id") + "";
                data[i][1] = rs.getString("name");
                data[i][2] = rs.getInt("age") + "";

                i++;
            }

            DefaultTableModel model = new DefaultTableModel(data, cols);
            personsTable.setModel(model);
        } catch (Exception e) {

            JOptionPane.showConfirmDialog(this, e, "Persons CRUDE", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void getSelectedRecord() {
        try {
            String str = personsTable.getValueAt(personsTable.getSelectedRow(), 0).toString();
            ResultSet rs = smt.executeQuery("select * from persons where status = 1 and id = "+str);
            
            if(rs.next())
            {
                recordTextField.setText("ID:"+rs.getInt("id")+""+"    NAME:"+ rs.getString("name") +"    AGE:"+ rs.getInt("age")+"");
                
            }
        } catch (Exception e) 
        {
                        JOptionPane.showConfirmDialog(this, e, "Persons CRUDE", JOptionPane.ERROR_MESSAGE);

        }
    }
}
